# Description of what this change includes
# Revision number
# Date

AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating a VPC in the US-West-2 region with 3 Availability Zones'

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: 'Name'
          Value: 'VPC-dordia4175'

  MySubnetAZ1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: 'us-west-2a'
      Tags:
        - Key: 'Name'
          Value: 'Subnet-dordia4175-AZ1'

  MySubnetAZ2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: 'us-west-2b'
      Tags:
        - Key: 'Name'
          Value: 'Subnet-dordia4175-AZ2'

  MySubnetAZ3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '10.0.3.0/24'
      AvailabilityZone: 'us-west-2c'
      Tags:
        - Key: 'Name'
          Value: 'Subnet-dordia4175-AZ3'

  MyInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'InternetGateway-dordia4175'

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

Outputs:
  VPCId:
    Description: 'The ID of the VPC'
    Value: !Ref MyVPC
